stack: Stack.c stack_tests.c
	gcc -ansi -pedantic-errors -Wall -Wextra -g Stack.c stack_tests.c
	
scheduler:	
	gcc -ansi -pedantic-errors -Wall -Wextra -g scheduler_tests.c scheduler.c task.c dllist.c UID.c PQ.c sortedlist.c
	
pq:	
	gcc -ansi -pedantic-errors -Wall -Wextra -g PQ_tests.c PQ.c dllist.c sortedlist.c
	
bit_array:	
	gcc -ansi -pedantic-errors -Wall -Wextra -g bit_array.c barr_tests.c
	
circular_buffer:	
	gcc -ansi -pedantic-errors -Wall -Wextra -g  Cb.c Cb_tests.c

dllist:	
	gcc -ansi -pedantic-errors -Wall -Wextra -g dllist.c dllist_tests.c
	
queue:	
	gcc -ansi -pedantic-errors -Wall -Wextra -g Queue.c queue_tests.c SList.c

slist:	
	gcc -ansi -pedantic-errors -Wall -Wextra -g SList.c slist_tests.c

sortedlist:	
	gcc -ansi -pedantic-errors -Wall -Wextra -g sortedlist.c sortedlist_tests.c PQ.c dllist.c
	
UID:	
	gcc -ansi -pedantic-errors -Wall -Wextra -g UID.c UID_tests.c
	
vector:	
	gcc -ansi -pedantic-errors -Wall -Wextra -g Vector.c vector_tests.c

