watcher: watcher.c
	gcc -ansi -pedantic-errors -Wall -Wextra -g watcher.c -lDS_Debug -I/home/student/chen-rubin/ds/scheduler -I/home/student/chen-rubin/ds/uid -L/home/student/chen-rubin/ds/ -Wl,-rpath=/home/student/chen-rubin/ds/ -lm -pthread
