watcher: watcher.c
	gcc -ansi -pedantic-errors -Wall -Wextra -g watcher.c -lDS_Debug -I/home/student/chen-rubin/ds/scheduler -I/home/student/chen-rubin/ds/uid -L/home/student/chen-rubin/ds/ -I/home/student/chen-rubin/chen/ -Wl,-rpath=/home/student/chen-rubin/ds/ -lm -pthread




#	gcc -ansi -pedantic-errors -Wall -Wextra -g watcher.c -lDS_Debug -I/home/chenr/git/ds/scheduler -I/home/chenr/git/ds/uid -L/home/chenr/git/ds/ -Wl,-rpath=/home/chenr/git/ds/ -lm -pthread
