watcher: watcher.c
	gcc -ansi -pedantic-errors -Wall -Wextra -g watcher.c wd_utils.c -lDS_Debug -I/home/student/chen-rubin/ds/scheduler -I/home/student/chen-rubin/ds/uid -L/home/student/chen-rubin/ds/ -I/home/student/chen-rubin/chen/ -Wl,-rpath=/home/student/chen-rubin/ds/ -lm -pthread

wd: wd.c
	gcc -ansi -pedantic-errors -Wall -Wextra -g wd.c wd_utils.c -lDS_Debug -I/home/student/chen-rubin/ds/scheduler -I/home/student/chen-rubin/ds/uid -I/home/student/chen-rubin/chen/ -L/home/student/chen-rubin/ds/ -Wl,-rpath=/home/student/chen-rubin/ds/ -lm -pthread -o wd.out


#watcher: watcher.c
#	gcc -ansi -pedantic-errors -Wall -Wextra -g watcher.c -lDS_Debug -I/home/chenr/git/ds/scheduler -I/home/chenr/git/ds/uid -I/home/chenr/git/chen/ -L/home/chenr/git/ds/ -Wl,-rpath=/home/chenr/git/ds/ -lm -pthread
	
#wd: wd.c
#	gcc -ansi -pedantic-errors -Wall -Wextra -g wd.c -lDS_Debug -I/home/chenr/git/ds/scheduler -I/home/chenr/git/ds/uid -I/home/chenr/git/chen/ -L/home/chenr/git/ds/ -Wl,-rpath=/home/chenr/git/ds/ -lm -pthread	-o wd.out
	
#	gcc -ansi -pedantic-errors -Wall -Wextra -g watcher.c -lDS_Debug -I/home/student/chen-rubin/ds/scheduler -I/home/student/chen-rubin/ds/uid -L/home/student/chen-rubin/ds/ -I/home/student/chen-rubin/chen/ -Wl,-rpath=/home/student/chen-rubin/ds/ -lm -pthread
